name: CI/CD Pipeline for Data Engineering

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List directory contents
        run: |
          ls -la
          ls -la cicd

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Format with black
        run: |
          black --check .

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests
        run: |
          pytest cicd/tests

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run integration tests
        run: |
          pytest cicd/tests/integration

  build:
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t cicd cicd

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Deploy to Cloud
        run: |
          docker tag cicd:latest my-docker-repo/cicd:latest
          docker push my-docker-repo/cicd:latest

  airflow:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Airflow
        run: |
          cd cicd
          docker-compose up -d

  dbt:
    runs-on: ubuntu-latest
    needs: airflow
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dbt
        run: |
          pip install dbt

      - name: Run dbt models
        run: |
          cd cicd
          dbt run

  spark:
    runs-on: ubuntu-latest
    needs: dbt
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Spark
        run: |
          wget https://archive.apache.org/dist/spark/spark-3.1.2/spark-3.1.2-bin-hadoop3.2.tgz
          tar xvf spark-3.1.2-bin-hadoop3.2.tgz
          export SPARK_HOME=$(pwd)/spark-3.1.2-bin-hadoop3.2
          export PATH=$SPARK_HOME/bin:$PATH

      - name: Run Spark job
        run: |
          spark-submit --master local[4] cicd/jobs/spark_job.py
